//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-05-03 15:23:22 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using CoreLand.Framework.EF.Entities;
using System.ComponentModel.DataAnnotations.Schema;
namespace EIP.News.Entity
{
    /// <summary>
    /// 流程专业审核结果记录表
    /// </summary>
    public class BusinessUnitApproved : EFEntity<Guid>
    {
        public BusinessUnitApproved()
        {
            Id = Guid.NewGuid();
        }

        /// <summary>
        /// ID
        /// 不能为空
        /// </summary>	
        [Key, Required]
        public override Guid Id { get; set; }

        /// <summary>
        /// 新闻ID
        /// 不能为空
        /// </summary>	
        [Required]
        public Guid ArticleId { get; set; }

        /// <summary>
        /// 人员ID
        /// 不能为空
        /// </summary>	
        [Required]
        public int UserId { get; set; }

        /// <summary>
        /// 审批意见
        /// </summary>
        [Required]
        public string Opinion { get; set; }

        /// <summary>
        /// 审批状态（true通过，false未通过）
        /// </summary>
        public bool? IsPass { get; set; }
    }
}